spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/myapp?useUnicode=yes&characterEncoding=UTF-8&useSSL=true&verifyServerCertificate=false&createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
  jpa:
    show-sql: ${SHOW_SQL:false}
    database-platform: com.service.webapp.util.MySQL57InnoDBDialectUtf8mb4 #org.hibernate.dialect.MySQL57Dialect #spring boot2中不加这句则默认为myisam引擎，参考类注释
    hibernate:
      ddl-auto: update
#      type: trace
#关于ddl-auto的设置
#create
# 启动时删数据库中的表，然后创建，退出时不删除数据表
#create-drop
# 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
#update
# 最常用的属性，第一次加载hibernate时根据model类会自动建立起表的结构（前提是先建立好数据库），以后加载hibernate时根据 model类自动更新表结构，即使表结构改变了但表中的行仍然存在不会删除以前的行。要注意的是当部署到服务器后，表结构是不会被马上建立起来的，是要等 应用第一次运行起来后才会。
#validate
# 项目启动表结构进行校验 如果不一致则报错
    
myapp:
  authentication:
    enable: ${AUTH_ENABLE:true}
    issuer: ${ISSUER:apiserver}
    tokenExpiredSeconds: ${TOKEN_EXPIRED_SECONDS:600}
    refreshTokenExpiredSeconds: ${REFRESH_TOKEN_EXPIRED_SECONDS:86400}
    white-list-type: normal
    white-list: "/api/v1/swagger.json:GET|POST,/api/v1/health:GET|POST,/api/v1/user/login:POST,/api/v1/user/refreshtoken:POST"

logging:
  level:
    root: INFO
    myapp: INFO
    org:
      hibernate:
#        type: TRACE  # 显示SQL Query取出的每个字段的数据类型
        SQL: DEBUG  # 显示SQL
  #file: /var/log/myapp.log
  pattern:
    webapp: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{requestId}] %logger{15} - %msg%n'  